### ISSUE TITLE
Problem with the Heatmap plus Row-dendrogram plot

### ISSUE THREAD

**Issue by freko247** [rasbt/pattern_classification#41]
There's a problem with the Heatmap plus Row-dendrogram plot in the Hierarchical Agglomerative Clustering - Complete Linkage Clustering notebook. The dendrogram is actually up-side-down, I noticed this when I was using your example as a guide. My fix was to reverse the index of the data and the index labels, I could not find a clever way of reversing the dendrogram. Thanks for a great guide anyway.
![selection_002](https://cloud.githubusercontent.com/assets/2719304/7175958/3a127568-e41a-11e4-9bf2-213805db1820.png)

**Comment by rasbt** [comment]
Thanks a lot for pointing this out. I think this can be accounted for by setting the `count_sort` order to `'descending'` in the dendrogram or sort the DataFrame in reverse order using the dendrogram leave indices. I corrected the sections and added some explanations and a warning at the end to always check that the labels match before hiding the dendrogram labels, e.g.,

![screen shot 2015-04-16 at 8 11 21 pm](https://cloud.githubusercontent.com/assets/5618407/7193948/6858cd72-e475-11e4-93d2-6c84d4159e6c.png)

Thanks,
Sebastian
