### ISSUE TITLE
Mistake to Pearson Correlation Coefficient formula

### ISSUE THREAD

**Issue by camxcube** [rasbt/pattern_classification#50]
I think the Correlation - Pearson formula in [this page](https://github.com/rasbt/pattern_classification/blob/master/resources/latex_equations.md#correlation---pearson) is wrong.

The formula you showed in the page is:

$$r = \frac{{}\sum_{i=1}^{n} (x_i - \overline{x})(y_i - \overline{y})}
{\sqrt{\sum_{i=1}^{n} (x_i - \overline{x})^2(y_i - \overline{y})^2}}$$

The correct one should be:

$$r = \frac{\sum_{i=1}^{n} (x_i - \overline{x})(y_i - \overline{y})}
{\sqrt{{\sum_{i=1}^{n} (x_i - \overline{x})^2}{\sum_{i=1}^{n} (y_i - \overline{y})^2}}}$$

**Comment by rasbt** [comment]
Thanks for the note! I just updated it!
